# Generated by Django 5.2.1 on 2025-06-03 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('highlighted_text', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('primary_button_text', models.CharField(max_length=50)),
                ('primary_button_link', models.URLField()),
                ('secondary_button_text', models.CharField(blank=True, max_length=50)),
                ('secondary_button_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Impact', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='mission/')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='services/icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link_text', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ImpactHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='impact/icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link_text', models.CharField(default='Read More', max_length=50)),
                ('link', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='home.impactsection')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='home.impactsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
